- root/etc/e-smith/events/actions/nethserver-webtop5-auth
- root/etc/e-smith/templates/usr/share/webtop/sql/data/init-data-core.sql/40settings
> conf: fix vmail secret password field

- createlinks
- root/etc/e-smith/events/actions/nethserver-webtop5-auth
- root/etc/e-smith/events/actions/nethserver-webtop5-conf
- root/etc/e-smith/events/actions/nethserver-webtop5-conf-db
> conf: enable sort of mail folder

- root/etc/e-smith/templates/usr/share/webtop/sql/data/init-data-core.sql/20users
> default config: remove ACCOUNT_SETTINGS permission

- root/etc/systemd/system/tomcat@.service.d/webtop.conf
> tomcat@webtop: cleanup cache on restart

- root/usr/share/webtop/doc/mb2md.pl
- root/usr/share/webtop/doc/pst2webtop.sh
- root/usr/share/webtop/doc/pst2webtop_cal.php
- root/usr/share/webtop/doc/pst2webtop_card.php
NethServer/dev#5244
Known limitations:
- for each recurring message of the .PST, the script will create n events until 2038
- Outlook reminders on event will are ignored
See also: http://community.nethserver.org/t/import-pst-email-contacts-and-calendar-to-webtop-5/7287/1
PR opened for: @nethcman and @lucagasparini
> Add script for PST import

- root/etc/e-smith/events/actions/nethserver-webtop5-conf-db
> db initialization: fix nextcloud service_id

- nethserver-webtop5.spec
- root/var/lib/tomcats/webtop/conf/server.xml
NethServer/dev#5338
See also NethServer/webtop5#3
> Avoid automatic deploy for future releases

- root/etc/e-smith/templates/usr/share/webtop/z-push/backend/webtop/config.php/30options
> z-push: add SONICLE_REST_BASE_URL for wt-5.1.1

- createlinks
- root/etc/e-smith/events/actions/nethserver-webtop5-conf-db
> Sync default.folder.spam value to SpamFolder prop value

- root/etc/e-smith/events/actions/nethserver-webtop5-conf
Find output is not uniformly sorted on different filesytems.
NethServer/dev#5405
> Fix sorting order on sql execution

- nethserver-webtop5.spec
> spec: require new webtop5 package

- root/etc/e-smith/templates/etc/sysconfig/tomcat@webtop/20java17
> Force webtop instance to use java 1.7

- root/etc/e-smith/events/actions/nethserver-webtop5-conf-db
- root/var/lib/tomcats/webtop/conf/server.xml
- Change default protocol in tomcat
- Insert new default setting for ACL IMAP lowercsae
> Changes default

- nethserver-webtop5.spec
> rpm spec: increase webtop minimum required version

- nethserver-webtop5.spec
> Add WebDav requirements

- root/etc/logrotate.d/webtop
- root/var/lib/tomcats/webtop/conf/logging.properties
- root/var/lib/tomcats/webtop/conf/server.xml
> Webtop tomcat logrotate

- root/etc/logrotate.d/webtop
> Remove tomcat webtop logs older than 2 days and other logrotate clean ups

- README.rst
- root/etc/e-smith/events/actions/nethserver-webtop5-conf-db
> config: set davserver.url option

- createlinks
- root/etc/e-smith/events/actions/nethserver-webtop5-clean-logs
Clean /var/lib/tomcats/webtop/logs/ directory from old and pre logrotate log files
NethServer/dev/issues/5516
> Add nethserver-webtop5-clean-logs action

- README.rst
- root/etc/e-smith/events/actions/nethserver-webtop5-conf-db
Add pbx.provider and pbx.provider.nethvoice.webrest.url
NethServer/dev#5516
> config: add PBX related options

- root/etc/e-smith/templates/etc/sysconfig/tomcat@webtop/10base
Disable endpoint identification on LDAPS connections.
Ref: https://redmine.sonicle.com/issues/539
NethServer/dev#5560
> Fix LDAPS CertificateException

- root/etc/e-smith/events/actions/nethserver-webtop5-conf-db
This should fix existing installation affected by https://redmine.sonicle.com/issues/541.
NethServer/dev#5570
> update: apply fix for upstream bug 541

- README.rst
- root/etc/e-smith/db/configuration/defaults/webtop/SmtpAuth
- root/etc/e-smith/db/configuration/defaults/webtop/SmtpStarttls
- root/etc/e-smith/events/actions/nethserver-webtop5-conf-db
> config: add smtp auth options

- README.rst
- root/etc/e-smith/db/configuration/defaults/webtop/RemoteCalendarAutosync
- root/etc/e-smith/db/configuration/defaults/webtop/RemoteCalendarAutosyncOnlywhenonline
- root/etc/e-smith/db/configuration/defaults/webtop/RemoteCategoryAutosync
- root/etc/e-smith/db/configuration/defaults/webtop/RemoteCategoryAutosyncOnlywhenonline
- root/etc/e-smith/events/actions/nethserver-webtop5-conf-db
> config: add remote calendar/categories autosync options

- createlinks
https://github.com/NethServer/dev/issues/5600
> Webtop subscribes to sssd-save event

- root/etc/e-smith/templates/etc/sysconfig/tomcat@webtop/10base
Fix for this bug: https://redmine.sonicle.com/issues/585
> Added for javamail parsing

- root/usr/share/webtop/sql/data/init-data-nethserver.sql
> config: disable statistic fields in event window

- createlinks
- nethserver-webtop5.spec
Centos 7.6 remove php 5.6
NethServer/dev#5666
> rpm spec: switch from php 5.6 to php 7.1

- nethserver-webtop5.spec
Add nethserver-rh-php71-php-fpm requirement.
NethServer/dev#5666
> rpm spec: add missing php 7.1 requirement.

- root/etc/e-smith/events/actions/nethserver-webtop5-conf
> conf action: make sure file_types table is not empty

- root/usr/share/webtop/sql/data/init-data-nethserver.sql
- root/usr/share/webtop/updates/pre/webtop-mail-settings.sql
Only for new installations, for older installations will be preserved
the previous default to "false"
NethServer/dev#5770
> config: enable compact toolbar as default

- root/usr/share/webtop/doc/pst2webtop_card.php
> pst2webtop_card.php: add display_name field

- root/etc/e-smith/events/actions/nethserver-webtop5-conf-db
- root/etc/e-smith/templates/etc/sysconfig/tomcat8@webtop/10base
- Clean up obsolete startup flags and rename deprecate flags
- Ensure that the default contacts ordering is by last name
- Enable Frontend JS optimizations
NethServer/dev#5770
> Startup flags clean up and configs

- root/usr/share/webtop/doc/pst2webtop_card.php
> pst2webtop_card.php: fix display_name concat

- nethserver-webtop5.spec
- root/etc/sudoers.d/50_nsapi_nethserver_webtop5
> Cockpit config for sudoers delegation

- nethserver-webtop5.spec
NethServer/dev#5928
Merge after release of https://github.com/NethServer/webtop5/pull/46
> Require webtop5 1.4.2

- root/opt/puppetlabs/puppet/lib/ruby/2.1.0/facter/webtop.rb
Reported data:
- count of users, calendars, shares and  contacts
- list of web browser agents
- virtual memory size in kB
- resident memory size in kB
NethServer/dev#5979
> Add inventory fact

- root/etc/e-smith/events/actions/nethserver-webtop5-conf-db
Fixed SMTP Starttls configuration into conf-db events.
Refer to https://github.com/NethServer/dev/issues/6018
> events. fix smtp starttls configuration value

- root/opt/puppetlabs/puppet/lib/ruby/2.1.0/facter/webtop.rb
> facter. avoid admins in users count

- nethserver-webtop5.spec
> spec: require webtop5 >= 1.4.6

- nethserver-webtop5.spec
> spec: require webtop5 >= 1.4.10

- nethserver-webtop5.spec
> spec: require webtop5 >= 1.4.12

- nethserver-webtop5.spec
> spec: require webtop5 >= 1.4.13

- nethserver-webtop5.spec
> spec: require webtop5 >= 1.4.14

- nethserver-webtop5.spec
> spec: require webtop5 >= 1.4.15

- root/etc/e-smith/events/actions/nethserver-webtop5-locale-tz
https://github.com/NethServer/dev/issues/6441
> cockpit ui. add languages in dropdown menu

- README.rst
- root/etc/e-smith/db/configuration/defaults/webtop/KnownDeviceVerification
- root/etc/e-smith/events/actions/nethserver-webtop5-conf-db
> config: add unknown-device notifications options

- root/etc/e-smith/templates/etc/webtop/webtop.properties/10base
- root/etc/logrotate.d/webtop
Write detailed authentication attempts into the
`/var/log/webtop/webtop_auth.log` log file.
NethServer/dev#6463
> Enable WebTop auth log file

- createlinks
- nethserver-webtop5.spec
- root/etc/e-smith/events/actions/nethserver-webtop5-conf-db
> Configure new Jitsi Meet integration

- createlinks
- root/etc/e-smith/events/actions/nethserver-webtop5-conf-db
- root/etc/e-smith/events/actions/nethserver-webtop5-conf-db-conference
* Add new action only for jitsi URL config
* don't restart WebTop on nethserver-conference-save
Any change of the conference's URL will be loaded and make visible on
user login time.
NethServer/dev#6463
> Refactor of Jitsi url setting

- nethserver-webtop5.spec
> spec: require webtop5 >= 1.4.16

- nethserver-webtop5.spec
> spec: require webtop5 >= 1.4.17

- nethserver-webtop5.spec
> spec: require webtop5 >= 1.4.19

- nethserver-webtop5.spec
> spec: require webtop5 >= 1.4.20

- nethserver-webtop5.spec
> spec: require webtop5 >= 1.4.21

- nethserver-webtop5.spec
> spec: require webtop5 >= 1.4.22

- root/etc/e-smith/events/actions/nethserver-webtop5-locale-tz
Refer to https://github.com/NethServer/dev/issues/6585 since new Webtop version include also French translation.
> cockpit ui. add french in dropdown menu

- nethserver-webtop5.spec
> spec: require webtop5 >= 1.4.25

- README.rst
- createlinks
- nethserver-webtop5.spec
- root/usr/share/webtop/bin/z-push-admin-wapper
PHP 7.3 SCL will be supported until EL7 EOL
NethServer/dev#6632
> conf & spec: switch to PHP 7.3

- nethserver-webtop5.spec
- root/etc/opt/rh/rh-php73/php-fpm.d/000-webtop.conf
Set custom memory limit to 1024M
NethServer/dev#6632
> conf: add custom fpm pool

- nethserver-webtop5.spec
> spec: require webtop5 >= 1.4.26

- nethserver-webtop5.spec
https://github.com/NethServer/dev/issues/6652
> spec: require webtop5 >= 1.4.27

- nethserver-webtop5.spec
> spec: require webtop5 >= 1.4.28

- root/etc/systemd/system/tomcat8@.service.d/webtop.conf
> systemd: add `postgresql` service as dependence

- createlinks
- root/etc/e-smith/events/actions/nethserver-webtop5-conf-db-spam_threshold
Get the value to from `db config rspmad SpamTag2Level`.
NethServer/dev#6674
> conf: set pas.spam.threshold option

- nethserver-webtop5.spec
> spec: require webtop5 >= 1.5.0

- nethserver-webtop5.spec
> spec: require webtop5 >= 1.5.1

- createlinks
- root/etc/e-smith/events/actions/nethserver-webtop5-fix-rsync-perms
> rsync: fix permissions and ownership issues

- nethserver-webtop5.spec
> spec: require webtop5 >= 1.5.2

- nethserver-webtop5.spec
> spec: require webtop5 >= 1.5.3

- nethserver-webtop5.spec
> spec: require webtop5 >= 1.5.4

- nethserver-webtop5.spec
- prep-sources
> spec: require webtop5 >= 1.5.5

- root/etc/e-smith/templates/etc/webtop/webtop.properties/10base
- root/usr/share/webtop/sql/data/init-data-nethserver.sql
See: https://sonicle.atlassian.net/browse/WT-1192
NethServer/dev#6736
> Deprecate home path in settings

- nethserver-webtop5.spec
>  spec: require webtop5 >= 1.5.6

- nethserver-webtop5.spec
> spec: require webtop5 >= 1.5.9

- nethserver-webtop5.spec
> spec: require webtop5 >= 1.5.10

- nethserver-webtop5.spec
> spec: require webtop5 >= 1.5.11

- nethserver-webtop5.spec
> spec: require webtop5 >= 1.5.12

- nethserver-webtop5.spec
> spec: require webtop5 >= 1.5.13
